package org.effectivejava.examples.chapter05.item27;

public class EliminateUncheckedWarnings {

    // In order to have more safe code, try to fix any warning generated by the compiler

    // If you think the code is safe or the warning isn't significant, you can
    // use then @SuppressWarnings("warning name"), @SafeVarargs ...

}
